apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  storageClassName:  manual
  capacity:
    storage: 1000Mi
  accessModes:
   - ReadWriteMany
  hostPath: 
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: weversoncelio/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost-found"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Senha123
        - name: MYSQL_DATABASE
          value: meubanco
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: weversoncelio/projeto-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
